### ISSUE TITLE
Panic in the leadership module

### ISSUE THREAD

**Issue by jeromegn** [fly-apps/postgres-ha#39]
This caused a restart of an instance:

```
[1;38;5;3msentinel[0m | [0;31mexit status 2[0m
[1;38;5;3msentinel[0m | 	/go/pkg/mod/github.com/superfly/leadership@v0.2.0/candidate.go:59 +0xa5
[1;38;5;3msentinel[0m | created by github.com/superfly/leadership.(*Candidate).RunForElection
[1;38;5;3msentinel[0m | 	/go/pkg/mod/github.com/superfly/leadership@v0.2.0/candidate.go:120 +0xc5
[1;38;5;3msentinel[0m | github.com/superfly/leadership.(*Candidate).campaign(0xc0001c8c40)
[1;38;5;3msentinel[0m | 	/go/pkg/mod/github.com/superfly/leadership@v0.2.0/candidate.go:94 +0x1a7
[1;38;5;3msentinel[0m | github.com/superfly/leadership.(*Candidate).initLock(0xc0001c8c40, 0x1b26d00, 0xc0001c0000, 0xc00003a020, 0x1)
[1;38;5;3msentinel[0m | goroutine 194689 [running]:
[1;38;5;3msentinel[0m |
[1;38;5;3msentinel[0m | panic: close of closed channel
```

Logs may be out of order, unsure! (bottom is most recent)

**Comment by davissp14** [comment]
This should be fixed in the latest release (v0.0.4).
