### ISSUE TITLE
Leader election exception in a single region cluster

### ISSUE THREAD

**Issue by jsierles** [fly-apps/postgres-ha#5]
As discussed @jeromegn, here's the exception from my Postgresql cluster:

```

021-06-08T08:55:05.602823410Z app[9f60ac6d] ams [info] sentinel          | 2021-06-08T08:55:05.598Z	INFO	cmd/sentinel.go:82	Trying to acquire sentinels leadership
2021-06-08T08:55:05.609339589Z app[9f60ac6d] ams [info] sentinel          | panic: close of closed channel
2021-06-08T08:55:05.609906867Z app[9f60ac6d] ams [info] sentinel          |
2021-06-08T08:55:05.610747063Z app[9f60ac6d] ams [info] sentinel          | goroutine 8321 [running]:
2021-06-08T08:55:05.612359433Z app[9f60ac6d] ams [info] sentinel          | github.com/superfly/leadership.(*Candidate).initLock(0xc0000e3b20, 0x0, 0x0, 0x0, 0x0)
2021-06-08T08:55:05.613847019Z app[9f60ac6d] ams [info] sentinel          | 	/go/pkg/mod/github.com/superfly/leadership@v0.2.1/candidate.go:98 +0x1a7
2021-06-08T08:55:05.615173484Z app[9f60ac6d] ams [info] sentinel          | github.com/superfly/leadership.(*Candidate).campaign(0xc0000e3b20)
2021-06-08T08:55:05.616694082Z app[9f60ac6d] ams [info] sentinel          | 	/go/pkg/mod/github.com/superfly/leadership@v0.2.1/candidate.go:124 +0xc5
2021-06-08T08:55:05.618096257Z app[9f60ac6d] ams [info] sentinel          | created by github.com/superfly/leadership.(*Candidate).RunForElection
2021-06-08T08:55:05.619688377Z app[9f60ac6d] ams [info] sentinel          | 	/go/pkg/mod/github.com/superfly/leadership@v0.2.1/candidate.go:60 +0xa5
2021-06-08T11:17:33.503055958Z app[9f60ac6d] ams [info] keeper            | 2021-06-08T11:17:33.496Z	ERROR	cmd/keeper.go:1010	error retrieving cluster data	{"error": "Unexpected response code: 429"}
2021-06-08T11:17:39.019360653Z app[9f60ac6d] ams [info] keeper            | 2021-06-08T11:17:39.015Z	ERROR	cmd/keeper.go:1010	error retrieving cluster data	{"error": "Unexpected response code: 429"}
2021-06-08T11:17:56.186520583Z app[9f60ac6d] ams [info] keeper            | 2021-06-08T11:17:56.179Z	ERROR	cmd/keeper.go:839	failed to update keeper info	{"error": "Unexpected response code: 429 (Your IP is issuing too many concurrent connections, please rate limit your calls\n)"}
2021-06-08T11:18:13.796358380Z app[d28f0578] ams [info] keeper            | 2021-06-08T11:18:13.788Z	ERROR	cmd/keeper.go:839	failed to update keeper info	{"error": "Unexpected response code: 429 (Your IP is issuing too many concurrent connections, please rate limit your calls\n)"}
```

**Comment by davissp14** [comment]
This is a `consul` specific issue and has to do with the client hitting its http connection limit, default is `200`.  New PG deploys will use Etcd by default, which should make this a non-issue going forward.

**Comment by davissp14** [comment]
Re-open if we see this again.
